/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface AbsenceDTO
 */
export interface AbsenceDTO {
    /**
     * 
     * @type {number}
     * @memberof AbsenceDTO
     */
    'id': number;
    /**
     * 
     * @type {UserTuple}
     * @memberof AbsenceDTO
     */
    'user': UserTuple;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDTO
     */
    'reason': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDTO
     */
    'dateFrom': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceDTO
     */
    'dateTo': string;
}

