/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AbsenceRequest
 */
export interface AbsenceRequest {
    /**
     * 
     * @type {string}
     * @memberof AbsenceRequest
     */
    'nick': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceRequest
     */
    'reason': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceRequest
     */
    'dateFrom': string;
    /**
     * 
     * @type {string}
     * @memberof AbsenceRequest
     */
    'dateTo': string;
}

