/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface BanRecordDTO
 */
export interface BanRecordDTO {
    /**
     * 
     * @type {number}
     * @memberof BanRecordDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'ip'?: string;
    /**
     * 
     * @type {UserTuple}
     * @memberof BanRecordDTO
     */
    'staff': UserTuple;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'reason'?: string;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'server': string;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'begin': string;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'end'?: string;
    /**
     * 
     * @type {number}
     * @memberof BanRecordDTO
     */
    'state': number;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'unbanDate'?: string;
    /**
     * 
     * @type {UserTuple}
     * @memberof BanRecordDTO
     */
    'unbanStaff'?: UserTuple;
    /**
     * 
     * @type {string}
     * @memberof BanRecordDTO
     */
    'unbanReason'?: string;
}

