/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CoinsLogDTO
 */
export interface CoinsLogDTO {
    /**
     * 
     * @type {number}
     * @memberof CoinsLogDTO
     */
    'balance': number;
    /**
     * 
     * @type {string}
     * @memberof CoinsLogDTO
     */
    'plugin': string;
    /**
     * 
     * @type {string}
     * @memberof CoinsLogDTO
     */
    'reason': string;
    /**
     * 
     * @type {number}
     * @memberof CoinsLogDTO
     */
    'present': number;
    /**
     * 
     * @type {string}
     * @memberof CoinsLogDTO
     */
    'time'?: string;
}

