/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface CoinsTransactionLogDTO
 */
export interface CoinsTransactionLogDTO {
    /**
     * 
     * @type {number}
     * @memberof CoinsTransactionLogDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CoinsTransactionLogDTO
     */
    'time'?: string;
    /**
     * 
     * @type {UserTuple}
     * @memberof CoinsTransactionLogDTO
     */
    'from': UserTuple;
    /**
     * 
     * @type {UserTuple}
     * @memberof CoinsTransactionLogDTO
     */
    'to': UserTuple;
    /**
     * 
     * @type {number}
     * @memberof CoinsTransactionLogDTO
     */
    'amount': number;
}

