/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO {
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    'groupName': string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    'groupDisplay': string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    'expiration'?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupDTO
     */
    'priority': number;
}

