/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JWTToken
 */
export interface JWTToken {
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof JWTToken
     */
    'expire': string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof JWTToken
     */
    'attributes': { [key: string]: string; };
}

