/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GroupDTO } from './group-dto';
import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface MediaEntryDTO
 */
export interface MediaEntryDTO {
    /**
     * 
     * @type {UserTuple}
     * @memberof MediaEntryDTO
     */
    'user': UserTuple;
    /**
     * 
     * @type {GroupDTO}
     * @memberof MediaEntryDTO
     */
    'group': GroupDTO;
    /**
     * 
     * @type {string}
     * @memberof MediaEntryDTO
     */
    'link'?: string;
}

