/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MigrateDelayDTO
 */
export interface MigrateDelayDTO {
    /**
     * 
     * @type {string}
     * @memberof MigrateDelayDTO
     */
    'startTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof MigrateDelayDTO
     */
    'endTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof MigrateDelayDTO
     */
    'delay': number;
}

