/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MigrateLogDTO
 */
export interface MigrateLogDTO {
    /**
     * 
     * @type {number}
     * @memberof MigrateLogDTO
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof MigrateLogDTO
     */
    'oldNickname': string;
    /**
     * 
     * @type {string}
     * @memberof MigrateLogDTO
     */
    'newNickname': string;
    /**
     * 
     * @type {string}
     * @memberof MigrateLogDTO
     */
    'uuidChanged': string;
    /**
     * 
     * @type {string}
     * @memberof MigrateLogDTO
     */
    'uuidFrom': string;
    /**
     * 
     * @type {string}
     * @memberof MigrateLogDTO
     */
    'time': string;
}

