/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MinigameStat } from './minigame-stat';

/**
 * 
 * @export
 * @interface Minigame
 */
export interface Minigame {
    /**
     * 
     * @type {string}
     * @memberof Minigame
     */
    'name': string;
    /**
     * 
     * @type {Array<MinigameStat>}
     * @memberof Minigame
     */
    'stats': Array<MinigameStat>;
}

