/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PredefinedMessage
 */
export interface PredefinedMessage {
    /**
     * 
     * @type {number}
     * @memberof PredefinedMessage
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PredefinedMessage
     */
    'uuid'?: string;
    /**
     * 
     * @type {string}
     * @memberof PredefinedMessage
     */
    'shortname': string;
    /**
     * 
     * @type {string}
     * @memberof PredefinedMessage
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof PredefinedMessage
     */
    'priority': number;
    /**
     * 
     * @type {string}
     * @memberof PredefinedMessage
     */
    'ticketType': string;
    /**
     * 
     * @type {number}
     * @memberof PredefinedMessage
     */
    'reward': number;
}

