/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MigrateLogDTO } from './migrate-log-dto';

/**
 * 
 * @export
 * @interface ResponsePageMigrateLogDTO
 */
export interface ResponsePageMigrateLogDTO {
    /**
     * 
     * @type {number}
     * @memberof ResponsePageMigrateLogDTO
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ResponsePageMigrateLogDTO
     */
    'totalElements': number;
    /**
     * 
     * @type {Array<MigrateLogDTO>}
     * @memberof ResponsePageMigrateLogDTO
     */
    'content': Array<MigrateLogDTO>;
}

