/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TicketInfo } from './ticket-info';

/**
 * 
 * @export
 * @interface ResponsePageTicketInfo
 */
export interface ResponsePageTicketInfo {
    /**
     * 
     * @type {number}
     * @memberof ResponsePageTicketInfo
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ResponsePageTicketInfo
     */
    'totalElements': number;
    /**
     * 
     * @type {Array<TicketInfo>}
     * @memberof ResponsePageTicketInfo
     */
    'content': Array<TicketInfo>;
}

