/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MuteRecordDTO } from './mute-record-dto';

/**
 * 
 * @export
 * @interface ResponsePageMuteRecordDTO
 */
export interface ResponsePageMuteRecordDTO {
    /**
     * 
     * @type {number}
     * @memberof ResponsePageMuteRecordDTO
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ResponsePageMuteRecordDTO
     */
    'totalElements': number;
    /**
     * 
     * @type {Array<MuteRecordDTO>}
     * @memberof ResponsePageMuteRecordDTO
     */
    'content': Array<MuteRecordDTO>;
}

