/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BanRecordDTO } from './ban-record-dto';

/**
 * 
 * @export
 * @interface ResponsePageBanRecordDTO
 */
export interface ResponsePageBanRecordDTO {
    /**
     * 
     * @type {number}
     * @memberof ResponsePageBanRecordDTO
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ResponsePageBanRecordDTO
     */
    'totalElements': number;
    /**
     * 
     * @type {Array<BanRecordDTO>}
     * @memberof ResponsePageBanRecordDTO
     */
    'content': Array<BanRecordDTO>;
}

