/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CoinsLogDTO } from './coins-log-dto';

/**
 * 
 * @export
 * @interface ResponsePageCoinsLogDTO
 */
export interface ResponsePageCoinsLogDTO {
    /**
     * 
     * @type {number}
     * @memberof ResponsePageCoinsLogDTO
     */
    'totalPages': number;
    /**
     * 
     * @type {number}
     * @memberof ResponsePageCoinsLogDTO
     */
    'totalElements': number;
    /**
     * 
     * @type {Array<CoinsLogDTO>}
     * @memberof ResponsePageCoinsLogDTO
     */
    'content': Array<CoinsLogDTO>;
}

