/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TicketParamType } from './ticket-param-type';

/**
 * 
 * @export
 * @interface TicketParam
 */
export interface TicketParam {
    /**
     * 
     * @type {string}
     * @memberof TicketParam
     */
    'name': string;
    /**
     * 
     * @type {TicketParamType}
     * @memberof TicketParam
     */
    'type': TicketParamType;
    /**
     * 
     * @type {number}
     * @memberof TicketParam
     */
    'maxLength': number;
}

