/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TicketRating
 */
export interface TicketRating {
    /**
     * 
     * @type {string}
     * @memberof TicketRating
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof TicketRating
     */
    'ticket': string;
    /**
     * 
     * @type {number}
     * @memberof TicketRating
     */
    'ratingGrade': number;
    /**
     * 
     * @type {string}
     * @memberof TicketRating
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof TicketRating
     */
    'respondent': string;
    /**
     * 
     * @type {string}
     * @memberof TicketRating
     */
    'note': string;
}

