/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TicketMessageDTO } from './ticket-message-dto';
import { TicketRating } from './ticket-rating';
import { UserTuple } from './user-tuple';
import { WrappedMessage } from './wrapped-message';

/**
 * 
 * @export
 * @interface TicketDTO
 */
export interface TicketDTO {
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'uid': string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'date': string;
    /**
     * 
     * @type {UserTuple}
     * @memberof TicketDTO
     */
    'author': UserTuple;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'type': string;
    /**
     * 
     * @type {WrappedMessage}
     * @memberof TicketDTO
     */
    'message': WrappedMessage;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'closedDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    'state': number;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    'group': number;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'params'?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'lastUpdate': string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'lastMessageTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    'starred': number;
    /**
     * 
     * @type {number}
     * @memberof TicketDTO
     */
    'duplicate': number;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof TicketDTO
     */
    'rateDate'?: string;
    /**
     * 
     * @type {TicketRating}
     * @memberof TicketDTO
     */
    'rating'?: TicketRating;
    /**
     * 
     * @type {Array<TicketMessageDTO>}
     * @memberof TicketDTO
     */
    'ticketMessages'?: Array<TicketMessageDTO>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TicketDTO
     */
    'attachments': Array<string>;
}

