/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TicketGroup } from './ticket-group';
import { TicketParam } from './ticket-param';

/**
 * 
 * @export
 * @interface TicketType
 */
export interface TicketType {
    /**
     * 
     * @type {string}
     * @memberof TicketType
     */
    'displayName': string;
    /**
     * 
     * @type {Array<TicketParam>}
     * @memberof TicketType
     */
    'ticketParams': Array<TicketParam>;
    /**
     * 
     * @type {TicketGroup}
     * @memberof TicketType
     */
    'defaultTicketGroup': TicketGroup;
    /**
     * 
     * @type {boolean}
     * @memberof TicketType
     */
    'canChangeGroup': boolean;
    /**
     * 
     * @type {string}
     * @memberof TicketType
     */
    'name': string;
    /**
     * 
     * @type {boolean}
     * @memberof TicketType
     */
    'canCreateTicket': boolean;
    /**
     * 
     * @type {string}
     * @memberof TicketType
     */
    'ticketTypeCategoryName': string;
}

