/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TicketFilters
 */
export interface TicketFilters {
    /**
     * 
     * @type {Array<number>}
     * @memberof TicketFilters
     */
    'id'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TicketFilters
     */
    'state'?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof TicketFilters
     */
    'group'?: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof TicketFilters
     */
    'author'?: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof TicketFilters
     */
    'starred'?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof TicketFilters
     */
    'type'?: Array<string>;
}

