/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface UnbanRequestDTO
 */
export interface UnbanRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'uid': string;
    /**
     * 
     * @type {UserTuple}
     * @memberof UnbanRequestDTO
     */
    'nick'?: UserTuple;
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'requesterIp'?: string;
    /**
     * 
     * @type {UserTuple}
     * @memberof UnbanRequestDTO
     */
    'requester': UserTuple;
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'time': string;
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'reason': string;
    /**
     * 
     * @type {string}
     * @memberof UnbanRequestDTO
     */
    'state': UnbanRequestDTOStateEnum;
    /**
     * 
     * @type {UserTuple}
     * @memberof UnbanRequestDTO
     */
    'processor'?: UserTuple;
}

/**
    * @export
    * @enum {string}
    */
export enum UnbanRequestDTOStateEnum {
    NEW = 'NEW',
    APPROVED = 'APPROVED',
    DENIED = 'DENIED'
}


