/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GroupDTO } from './group-dto';

/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'uuid': string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'nickname': string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'lastIp'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'minecraftUUID'?: string;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'ipWhitelist': number;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'isPremium': number;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'souhlas': number;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'firstLogin'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    'lastLogin': string;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'onlineTime': number;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'coins': number;
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    'cratesAmount': number;
    /**
     * 
     * @type {GroupDTO}
     * @memberof UserProfile
     */
    'group': GroupDTO;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    'hasEmail': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserProfile
     */
    'registered': boolean;
}

