/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ParentMinigame } from './parent-minigame';
import { UserTuple } from './user-tuple';

/**
 * 
 * @export
 * @interface UserSpecificStats
 */
export interface UserSpecificStats {
    /**
     * 
     * @type {UserTuple}
     * @memberof UserSpecificStats
     */
    'user': UserTuple;
    /**
     * 
     * @type {ParentMinigame}
     * @memberof UserSpecificStats
     */
    'parentMinigame': ParentMinigame;
}

