/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VIPCode
 */
export interface VIPCode {
    /**
     * 
     * @type {string}
     * @memberof VIPCode
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof VIPCode
     */
    'vipType': string;
    /**
     * 
     * @type {string}
     * @memberof VIPCode
     */
    'date': string;
    /**
     * 
     * @type {string}
     * @memberof VIPCode
     */
    'activationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof VIPCode
     */
    'duration': number;
}

