/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TicketMessageType } from './ticket-message-type';

/**
 * 
 * @export
 * @interface WrappedMessage
 */
export interface WrappedMessage {
    /**
     * 
     * @type {string}
     * @memberof WrappedMessage
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof WrappedMessage
     */
    'verifiedContent'?: string;
    /**
     * 
     * @type {number}
     * @memberof WrappedMessage
     */
    'predefined': number;
    /**
     * 
     * @type {TicketMessageType}
     * @memberof WrappedMessage
     */
    'type': TicketMessageType;
}

