/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ResultResponse } from '../models';
// @ts-ignore
import { Survey } from '../models';
// @ts-ignore
import { SurveyRequest } from '../models';
/**
 * SurveyControllerApi - axios parameter creator
 * @export
 */
export const SurveyControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSurvey: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/survey`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SurveyRequest} surveyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSurvey: async (surveyRequest: SurveyRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'surveyRequest' is not null or undefined
            assertParamExists('sendSurvey', 'surveyRequest', surveyRequest)
            const localVarPath = `/survey`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(surveyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SurveyControllerApi - functional programming interface
 * @export
 */
export const SurveyControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SurveyControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSurvey(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Survey>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSurvey(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {SurveyRequest} surveyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendSurvey(surveyRequest: SurveyRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendSurvey(surveyRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SurveyControllerApi - factory interface
 * @export
 */
export const SurveyControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SurveyControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSurvey(options?: any): AxiosPromise<Survey> {
            return localVarFp.getSurvey(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SurveyRequest} surveyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSurvey(surveyRequest: SurveyRequest, options?: any): AxiosPromise<ResultResponse> {
            return localVarFp.sendSurvey(surveyRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SurveyControllerApi - object-oriented interface
 * @export
 * @class SurveyControllerApi
 * @extends {BaseAPI}
 */
export class SurveyControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyControllerApi
     */
    public getSurvey(options?: AxiosRequestConfig) {
        return SurveyControllerApiFp(this.configuration).getSurvey(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SurveyRequest} surveyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyControllerApi
     */
    public sendSurvey(surveyRequest: SurveyRequest, options?: AxiosRequestConfig) {
        return SurveyControllerApiFp(this.configuration).sendSurvey(surveyRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
